### ISSUE TITLE
Load model configuration from a YAML file

### ISSUE THREAD

**Issue by jpn--** [quaquel/EMAworkbench#45]
Load model configuration in a generic way from a YAML file.

**Comment by quaquel** [comment]
do you have an example snippet of a yaml file you currently use?

**Comment by jpn--** [comment]
I am in the process of cleaning up to publish in the next couple days a whole mess of examples and the rest of the meta-model codebase we've been working on.  Will let you know when we put it up.

**Comment by quaquel** [comment]
I want to look at some loaders in general at some point so it is still of interest.

**Comment by mikhailsirenko** [comment]
Perhaps, let's start with just yaml? How about:

```
class Loader:
    @staticmethod
    def load_yaml(file_path):
        with open(file_path, 'r') as file:
            data = yaml.safe_load(file)
        
        uncertainties = []
        constants = []
        levers = []
        
        for parameter, value in data.get('uncertainties', {}).items():
            if 'type' in value:
                if value['type'] == 'real':
                    uncertainties.append(RealParameter(parameter, value['min'], value['max']))
                elif value['type'] == 'integer':
                    uncertainties.append(IntegerParameter(parameter, value['min'], value['max']))
                elif value['type'] == 'categorical':
                    uncertainties.append(CategoricalParameter(parameter, value['categories']))

        for parameter, value in data.get('constants', {}).items():
            constants.append(Constant(parameter, value))

        for parameter, value in data.get('levers', {}).items():
            if 'type' in value:
                if value['type'] == 'real':
                    levers.append(RealParameter(parameter, value['min'], value['max']))
                elif value['type'] == 'integer':
                    levers.append(IntegerParameter(parameter, value['min'], value['max']))
                elif value['type'] == 'categorical':
                    levers.append(CategoricalParameter(parameter, value['categories']))

        return uncertainties, constants, levers
```

For a yaml of the following format:

```
uncertainties:
    x1:
        type: real
        min: 0.1
        max: 10
    x2:
        type: real
        min: -0.01
        max: 0.01
    x3:
        type: real
        min: -0.01
        max: 0.01

constants:
    constant1: 10
    constant2: 20

levers:
    lever1:
        type: real
        min: 0.5
        max: 1.5
    lever2:
        type: integer
        min: 1
        max: 5
    lever3:
        type: categorical
        categories: [A, B, C]
```
